Implemented New Designs
secure-vote/sv-app pull request #64
Opened 2018-02-27 00:27 UTC by TomSesselmann

Updated all screens and added styling to the vote slider.

2018-02-27 00:27 UTC, TomSesselmann commented
@XertroV you don't need to go through all of it line by line, just see if there's anything obvious that you would do differently.

2018-03-01 07:03 UTC, XertroV commented on web/src/Components/Btn.elm
> +                -- TODO: Btn is not safely disabled. Can be removed with Dev Tools
That's fine - should have a check for appropriate conditions somewhere. Remember that a sophisticated user will just figure out how to issue the request manually if they want to.

Security and UX are two diff considerations, and we shouldn't handle security when thinking about UX stuff - that should be way deeper.

2018-03-01 07:04 UTC, XertroV commented on web/src/Components/IssueCard.elm
> +            ballot.state
this is super unclear and takes a lot of mental energy to parse - should be changed to testing elements, like `List.member ballot.state [BallotPendingCreation, BalltoPendingEdits, BallotPendingDelegation] || vote.state == Vote.Pending`

That's just one example - other ways to do it but this isn't good.

2018-03-01 07:05 UTC, XertroV commented on web/src/Components/IssueCard.elm
> +        struct =
if any of the following 20 lines is common it should be generated programatically - like there's a LOT of similar code here. Maybe use a make function mapping over a list of tuples or something.

2018-03-01 07:08 UTC, XertroV requested changes

2018-03-01 07:08 UTC, XertroV commented on web/src/Components/Slider.elm
> +                               , HA.min <| toString <| range.min
Should these be strings?

2018-03-01 07:08 UTC, XertroV commented on web/src/Components/IssueCard.elm
> +        struct =
This comment is just to make the above part of the review

2018-03-01 07:08 UTC, XertroV commented on web/src/Components/IssueCard.elm
> +            ballot.state
this comment is just to make the above part of the review

2018-03-01 07:08 UTC, XertroV commented on web/src/Components/Slider.elm
> +                    { l = 2, r = 13, txt = "Mostly Disagree" }
Why are these numbers here? they seem arbitrary...

2018-03-06 04:46 UTC, merged